In [6]:
import numpy as np

def sigmoid(x):
    return(1/(1+np.exp(-x)))
    
# 10 a)
# (i)
# define the matrix of weights

W = np.array([-0.8,0.5,1])
b=2
#define input x
x=np.array([1,-2,-1])
#compute the logit z

z = np.dot(W, x) + b
y = sigmoid(z)
#print(y)
#define input x
x=np.dot(W,x)+b
y=sigmoid(z)
print("(i)")
print(x,y)


#(ii)
#define the matrix of weights
W1=np.array([[0.8,-1,-0.4],[0.2,-2,-0.5]])
#define the vector of biases
b1=np.array([2,1])
#define the input x
x=np.array([0.4,-2.8,1.2])
#compute the logic
z1=np.dot(W1,x)+b1
a1=sigmoid(z1)
W2 = np.array([2,3])
b2=-1

z2=np.dot(W2, a1)+b2
y=sigmoid(z2)

print("(ii)")
print("Input =", x)
print("Hidden Layer Output =", a1)
print("Output =", y)



print("(iii)")
#(iii)

# define matrix of weights
W1 = np.array([[ 1, -1], [-1,  1]])

# define vector of biases
b1 = np.array([-1.2, -1.2])

# define input x
x = np.array([1, 0])

# compute hidden layer
z1 = np.dot(W1, x) + b1
a1 = sigmoid(z1)

# output layer weights
W2 = np.array([1, 1])

# output bias
b2 = -0.5

# compute output layer
z2 = np.dot(W2, a1) + b2
y = sigmoid(z2)

print("(iii)")
print("Input =", x)
print("Hidden Output =", a1)
print("Output =", y)

(i)
-0.7999999999999998 0.3100255188723876
(ii)
Input = [ 0.4 -2.8  1.2]
Hidden Layer Output = [0.99043468 0.99771705]
Output = 0.9815491292654628
(iii)
(iii)
Input = [1 0]
Hidden Output = [0.450166   0.09975049]
Output = 0.5124765324569702


In [8]:
import numpy as np

def sigmoid(x):
    return(1/(1+np.exp(-x)))
    
# Input values
x1 = 1
x2 = 2
x3 = 3

# Input vector
x = np.array([[x1],[x2],[x3]])

# Layer 1 : (x -> [-2, 4])

W1 = np.array([[ 0.8,  0.1, -0.6], [-0.5, -0.4,  1.2]])

b1 = np.array([[-2], [ 4]])

z1 = np.dot(W1, x) + b1
h1 = sigmoid(z1)

print("Layer 1 Output")
print(h1)


# Layer 2 : ([-2,4] -> [-2.5,1.5,-0.8,1.6])

W2 = np.array([[-1.2,  1.4],[ 0.6,  0.1],[-0.2,  0.5],[ 2.0, -1.5]])
b2 = np.array([[-2.5],[ 1.5],[-0.8],[ 1.6]])

z2 = np.dot(W2, h1) + b2
h2 = sigmoid(z2)

print("Layer 2 Output")
print(h2)


# Layer 3 : ([-2.5,1.5,-0.8,1.6] -> [-1.4,2.2])

W3 = np.array([[ 1.6,  0.1,  0.4, -0.4],[-1.0, -1.2,  0.8, -1.4]])

b3 = np.array([[-1.4],[ 2.2]])

z3 = np.dot(W3, h2) + b3
h3 = sigmoid(z3)

print("Layer 3 Output")
print(h3)


# Output Layer : ([-1.4,2.2] -> [-1,-2,-3])

W4 = np.array([[ 0.5,  0.8],[-1.2, -1.0],[-0.6, -0.2]])

b4 = np.array([[-1],[-2],[-3]])

z4 = np.dot(W4, h3) + b4
y = sigmoid(z4)

print("Final Output")
print(y)

Layer 1 Output
[[0.05732418]
 [0.99816706]]
Layer 2 Output
[[0.23661013]
 [0.83674572]
 [0.4225336 ]
 [0.55413639]]
Layer 3 Output
[[0.27083498]
 [0.62750568]]
Final Output
[[0.41033566]
 [0.04961813]
 [0.03598509]]


In [9]:
A=np.zeros((2,3))
print(A)

[[0. 0. 0.]
 [0. 0. 0.]]


In [18]:
#10d)
import numpy as np

def sigmoid(x):
    return 1/(1+np.exp(-x))

class layer():

    def __init__(self, n_inputs, n_neurons):
        self.n_inputs = n_inputs
        self.n_neurons = n_neurons
        self.weights = np.zeros((n_neurons, n_inputs))
        self.biases = np.zeros(n_neurons)

    def activations(self, x):
        return sigmoid(np.dot(self.weights, x) + self.biases)
   

In [27]:
#(i)
lay=layer(3,1)
lay.weights=np.array([-0.8,0.5,1])
lay.biases=2
x=np.array([1,-2,-1])
lay.activations(x)
print("(i)")
print(x,y)

#(ii)
lay1=layer(3,2)
lay1.weights=np.array([[0.8,-1,-0.4],[0.2,-2,-0.5]])
lay1.biases=np.array([2,1])
lay2=layer(2,1)
lay2.weights=np.array([[2,3]])
lay2.biases=-1
lay_list=[lay1,lay2]
x=np.array([0.4,-2.8,1.2])
a=x
for lay in lay_list:
    a=lay.activations(a)
y = a

print("(ii)")
print(x,y)



# (iii)
lay1 = layer(2,2)
lay1.weights = np.array([[ 1, -1],[-1,  1]])
lay1.biases = np.array([-1.2, -1.2])


lay2 = layer(2,1)
lay2.weights = np.array([[1,1]])
lay2.biases = np.array([-0.5])

# Input
x = np.array([1,-2])

a1 = lay1.activations(x)
y = lay2.activations(a1)

print("(iii)")
print(x,y)


(i)
[ 1 -2 -1] [0.59216508]
(ii)
[ 0.4 -2.8  1.2] [0.98154913]
(iii)
[ 1 -2] [0.59216508]


EXCERSICE 11

In [38]:
#11-1
import numpy as np

def grad_descent(x_start,f,f_prime,eta=0.1,iter=10):
    
    x=x_start
    for j in range(iter):
        x_star=x-eta*f_prime(x) #iteration step
        print(f"{j+1} {np.round(x,2)} {np.round(f_prime(x),2)} {np.round(x_star,2)} {np.round(f(x_star),2)}")
        x=x_star
        

In [40]:
#11-2a)
def f(x):
    return (x-2)**2+1
def f_prime(x):
    return 2*(x-2)
grad_descent(5.0,f,f_prime)
grad_descent(5.0,f,f_prime,eta=0.5)
grad_descent(5.0,f,f_prime,eta=1)

1 5.0 6.0 4.4 6.76
2 4.4 4.8 3.92 4.69
3 3.92 3.84 3.54 3.36
4 3.54 3.07 3.23 2.51
5 3.23 2.46 2.98 1.97
6 2.98 1.97 2.79 1.62
7 2.79 1.57 2.63 1.4
8 2.63 1.26 2.5 1.25
9 2.5 1.01 2.4 1.16
10 2.4 0.81 2.32 1.1
1 5.0 6.0 2.0 1.0
2 2.0 0.0 2.0 1.0
3 2.0 0.0 2.0 1.0
4 2.0 0.0 2.0 1.0
5 2.0 0.0 2.0 1.0
6 2.0 0.0 2.0 1.0
7 2.0 0.0 2.0 1.0
8 2.0 0.0 2.0 1.0
9 2.0 0.0 2.0 1.0
10 2.0 0.0 2.0 1.0
1 5.0 6.0 -1.0 10.0
2 -1.0 -6.0 5.0 10.0
3 5.0 6.0 -1.0 10.0
4 -1.0 -6.0 5.0 10.0
5 5.0 6.0 -1.0 10.0
6 -1.0 -6.0 5.0 10.0
7 5.0 6.0 -1.0 10.0
8 -1.0 -6.0 5.0 10.0
9 5.0 6.0 -1.0 10.0
10 -1.0 -6.0 5.0 10.0


In [41]:
#11-2b)
import numpy as np

def grad_descent(x_start,f,f_prime,eta=0.1,iter=10):
    x = x_start
    for j in range(iter):
        x_star = x - eta*f_prime(x)
        print(f"{j+1:2d}   {x:6.3f}   {f_prime(x):7.3f}   {x_star:7.3f}")
        x = x_star

In [43]:
def f(x):
    return 0.5*(x-2)**2*x*(x+2)

def f_prime(x):
    return 2*x**3 - 3*x**2 - 4*x + 4

grad_descent(0.0,f,f_prime,eta=0.1)
grad_descent(0.0,f,f_prime,eta=0.2)
grad_descent(0.0,f,f_prime,eta=1.0)

grad_descent(3.0,f,f_prime,eta=0.1)
grad_descent(3.0,f,f_prime,eta=0.2)
grad_descent(3.0,f,f_prime,eta=1.0)

 1    0.000     4.000    -0.400
 2   -0.400     4.992    -0.899
 3   -0.899     3.717    -1.271
 4   -1.271     0.133    -1.284
 5   -1.284    -0.046    -1.280
 6   -1.280     0.016    -1.281
 7   -1.281    -0.006    -1.281
 8   -1.281     0.002    -1.281
 9   -1.281    -0.001    -1.281
10   -1.281     0.000    -1.281
 1    0.000     4.000    -0.800
 2   -0.800     4.256    -1.651
 3   -1.651    -6.578    -0.336
 4   -0.336     4.929    -1.321
 5   -1.321    -0.565    -1.208
 6   -1.208     0.926    -1.393
 7   -1.393    -1.663    -1.061
 8   -1.061     2.479    -1.557
 9   -1.557    -4.588    -0.639
10   -0.639     4.809    -1.601
 1    0.000     4.000    -4.000
 2   -4.000   -156.000   152.000
 3   152.000   6953700.000   -6953548.000
 4   -6953548.000   -672433683697065000960.000   672433683697058054144.000
 5   672433683697058054144.000   608104722219855305082000277084819109953115760158831284372635648.000   -608104722219855305082000277084819109953115760158831284372635648.000
 6   -

OverflowError: (34, 'Result too large')

In [44]:
#11-2c)
def f(x):
    return (x[0]-2)**2 + (x[1]-2)**2 +1
def f_prime(x):
    return np.array([2*x[0]-1,2*x[-1]-4])
grad_descent(np.array([3,2]),f,f_prime, iter=20)

TypeError: unsupported format string passed to numpy.ndarray.__format__